### PR TITLE
Fix link to demo4 in colab badge

### PR DESCRIPTION
**Pull request by danibene**
Hi, thank you very much for developing this & making it accessible! 

I noticed that the colab badge for demo4 in the readme didn't work due to a typo.

### CODE REVIEW

**Comment by cofri** [comment]
@danibene Thanks for your contribution and for the good catch ;)
If you have any other change requests or suggestions for improvements, feel free to open an issue or a pull request.

**Review by cofri — APPROVED** [review]

**Comment by cofri** [comment]
By the way, the `README.md` you modified is partly duplicated in `docs/index.md`. Could you also fix the link there please?

**Comment by danibene** [comment]
> By the way, the `README.md` you modified is partly duplicated in `docs/index.md`. Could you also fix the link there please?

Done!

**Review by cofri — APPROVED** [review]
Thanks for your changes!

**Pull request merged**
